# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_interera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_design_interera',
            options={'verbose_name': '\u0413\u0410\u041b\u0415\u0420\u0415\u042e \u0414\u0418\u0417\u0410\u0419\u041d\u0410 \u0418\u041d\u0422\u0415\u0420\u042c\u0415\u0420\u0410', 'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f \u0434\u0438\u0437\u0430\u0439\u043d\u0430 \u0438\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='interer',
            options={'verbose_name': '\u0414\u0418\u0417\u0410\u0419\u041d \u0418\u041d\u0422\u0415\u0420\u042c\u0415\u0420\u0410', 'verbose_name_plural': '\u0434\u0438\u0437\u0430\u0439\u043d\u044b \u0438\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u043e\u0432'},
        ),
    ]
