# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects_home', '0005_auto_20170331_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430', max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
                ('location', models.CharField(max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='public_building')),
                ('name_rozdela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_home.Rozdel', verbose_name='\u0418\u043c\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='public_building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_building.Building')),
            ],
        ),
    ]
