# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': '\u041f\u0420\u041e\u0415\u041a\u0422 \u041e\u0411\u0429. \u041d\u0410\u0417\u041d\u0410\u0427.', 'verbose_name_plural': '\u041f\u0440\u043e\u0435\u0442\u044b \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='gallery_building',
            options={'verbose_name': '\u0413\u0410\u041b\u0415\u0420\u0415\u042e \u041f\u0420-\u041e\u0412 \u041e\u0411\u0429. \u041d\u0410\u0417\u041d\u0410\u0427.', 'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0438\u044f \u043f\u0440\u043e\u0435\u0442\u043e\u0432 \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'},
        ),
    ]
