# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430', max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
                ('location', models.CharField(max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='static/images/projects_home')),
            ],
        ),
    ]
