# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images/projects_home')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_home.Project_home')),
            ],
        ),
    ]
