# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_home', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_home',
            name='image',
            field=models.ImageField(upload_to='projects_home'),
        ),
    ]
