# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_home', '0003_auto_20170319_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430', max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
                ('location', models.CharField(max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='projects_home')),
            ],
        ),
        migrations.CreateModel(
            name='Rozdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0440\u0430\u0437\u0434\u0435\u043b\u0430')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_home.Project'),
        ),
        migrations.DeleteModel(
            name='Project_home',
        ),
        migrations.AddField(
            model_name='project',
            name='name_rozdela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_home.Rozdel'),
        ),
    ]
