# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_home', '0004_auto_20170329_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_rozdela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_home.Rozdel', verbose_name='\u0418\u043c\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430'),
        ),
    ]
