# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_home', '0005_auto_20170331_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '\u0413\u0410\u041b\u0415\u0420\u0415\u042e \u041f\u0420\u041e\u0415\u041a\u0422\u0410 \u0416\u0418\u041b\u041e\u0413\u041e \u0414\u041e\u041c\u0410', 'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432 \u0436\u0438\u043b\u044b\u0445 \u0434\u043e\u043c\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u041f\u0420\u041e\u0415\u041a\u0422 \u0416\u0418\u041b\u041e\u0413\u041e \u0414\u041e\u041c\u0410', 'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b \u0436\u0438\u043b\u044b\u0445 \u0434\u043e\u043c\u043e\u0432'},
        ),
    ]
