# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '\u041b\u041e\u0413\u041e\u0422\u0418\u041f \u041f\u0410\u0420\u0422\u041d\u0415\u0420\u041e\u0412', 'verbose_name_plural': '\u041b\u043e\u0433\u043e\u0442\u0438\u043f\u044b \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
